### ISSUE TITLE
Error: INSTALLATION FAILED: YAML parse error on opennms/templates/app-jks.secret.yaml: error converting YAML to JSON:

### ISSUE THREAD

**Issue by ae185110** [agalue/onms-k8s-poc#1] opened 2022-01-19 11:53 UTC
- After starting the dependencies successfully facing issue when running **helm install "-f helm-cloud.yaml"** with error message below:
(Error: INSTALLATION FAILED: YAML parse error on opennms/templates/app-jks.secret.yaml: error converting YAML to JSON: yaml: line 17: could not find expected ':')

 - Checked a lot of references stating there should be an indentation error (might need to use indent or nindent function to fix it).

- Full command:
helm install -f helm-cloud.yaml \
  --set domain=k8s.agalue.net \
  --set storageClass=onms-share \
  --set ingress.certManager.clusterIssuer=opennms-issuer \
  --set dependencies.truststore.content=$(cat jks/truststore.jks | base64) \
  --set dependencies.postgresql.ca_cert=$(cat jks/postgresql-ca.crt | base64) \
  --set dependencies.postgresql.hostname=onms-db.shared.svc \
  --set dependencies.kafka.hostname=onms-kafka-bootstrap.shared.svc \
  --set dependencies.elasticsearch.hostname=onms-es-http.shared.svc \
  apex1 ./opennms
  
  - Error screenshot 
<img width="943" alt="error" src="https://user-images.githubusercontent.com/95692973/150124491-d54ed9b3-dd16-4f17-bded-9bfa81353215.png">

**Comment by agalue** [comment] 2022-01-19 14:50
I tested it multiple times via Minikube, Microsoft Azure, and Google Cloud.

First, you should change the domain, as you don't own `agalue.net`, and you would need a wildcard entry in your DNS registrar to test it.

Also, watch out for the dependencies, especially the trust stores and certificates; those cannot be empty if you're going to pass them. I start all the dependencies on the `shared` namespace within K8s for testing purposes only, and the above assumes that. Is that the case on your end? You should provide valid FQDNs for your actual dependencies.

Finally, have you modified helm-cloud.yaml? That contains some defaults, overridden by the `--set` entries.

**Comment by deejgregor** [comment] 2022-11-17 16:27
@ae185110 did you see the previous response from agalue? Are you still having problems? If so, can you provide any more details, such as example files?

**Comment by deejgregor** [comment] 2022-12-21 20:10
Did not get a response from requester on last question. Closing.

Please re-open if the problem is still happening and provide details requested in https://github.com/opennms-forge/onms-k8s-poc/issues/1#issuecomment-1318891545

**Closed as completed by deejgregor** 2022-12-21 20:10 UTC
